server:
  address: localhost
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}

    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
      format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt :
  secret: ${JWT_SECRET}